---
title: "ABCD Model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

packages <-  c("tidyverse",
               "reshape2",
               "nlme", "lme4",
               "data.table", "psych",
               "parallel","lubridate",
               "ggpubr", "broom", 
               "apaTables", "MetBrewer", "beepr", "doParallel", "tictoc", "rsample", "tidymodels")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)
```




Data Import/Set-Up
```{r}
#load("Sample_1.Rds")
#load("Sample_2.Rds")
#load("renamed_smri_baseline.Rda")


#df_train_baseline <- filter(renamed_smri_baseline, src_subject_id %in% sample_1$src_subject_id)
#df_validation_baseline <- filter(renamed_smri_baseline, src_subject_id %in% sample_2$src_subject_id)

#save(df_train_baseline, file="df_train_baseline.Rds")
#save(df_validation_baseline, file="df_validation_baseline.Rds")

load("/Volumes/devbrainlab/Lucy/BrainAGE/fyp/analysis_sample_baseline.Rds")
load("/Volumes/devbrainlab/Lucy/BrainAGE/fyp/training_sample_baseline.Rds")
```

Test Model
```{r}
abcd_brainage_model <- readRDS("/Volumes/devbrainlab/Lucy/BrainAGE/fyp/xgboost_abcd_brain_age_mod_5_9.rds")
```

Predict Brain Age (baseline)
```{r}
brain_age_df_baseline <-
  abcd_brainage_model %>%
  predict(new_data = analysis_sample_baseline) %>%
  mutate(
    # provide the chronological age at time of scan
    truth = analysis_sample_baseline$interview_age
  ) %>%
  # compute the brain age gap by subtracting chronological age from prediction
  mutate(gap = .pred - truth)

```

Predict Brain Age (follow-up)
```{r}
brain_age_df_followup <-
  xgb_mod %>%
  predict(new_data = renamed_smri_followup) %>%
  mutate(
    # provide the chronological age at time of scan
    truth = renamed_smri_followup$interview_age
  ) %>%
  # compute the brain age gap by subtracting chronological age from prediction
  mutate(gap = .pred - truth)
```

Evaluate accuracy
```{r}
# compute common performance metrics: mae, rsq, rmse
brain_age_df_baseline %>%
  metrics(truth = truth, estimate = .pred)

brain_age_df_followup %>%
  metrics(truth = truth, estimate = .pred)
```

Optional bias correction
```{r}
# bias prediction method, steps in comments,
# previously determined values hardcoded.


#get validation set
set.seed(42)
df_split_baseline <- initial_split(
  training_sample_baseline, 
  prop = 0.80,
  # matching age distributions across train and test set
  strata = "interview_age"
)

df_train_baseline <- training(df_split_baseline)
df_validation_baseline <- testing(df_split_baseline)

describe(df_train_baseline)
describe(df_validation_baseline)


#think I need to now run model on validation set??
abcd_brain_age_correction <-
  abcd_brainage_model %>%
  predict(new_data = df_validation_baseline) %>%
  mutate(
    # provide the chronological age at time of scan
    truth = df_validation_baseline$interview_age
  ) %>%
  # compute the brain age gap by subtracting chronological age from prediction
  mutate(gap = .pred - truth)

#get MAE for hold-out 
abcd_brain_age_correction %>%
  metrics(truth = truth, estimate = .pred)



abcd_bias_mod_baseline <- lm(.pred ~ truth, data = abcd_brain_age_correction)

# extract intercept and slope
#abcd_bias_mod_baseline$coefficients[["(Intercept)"]]
abcd_bias_intercept_baseline <- 7.917289
#abcd_bias_mod_baseline$coefficients[["truth"]]
abcd_bias_slope_baseline <-  0.2017998

# create bias correct data frame
#Baseline
brain_age_corrected_df_baseline <- brain_age_df_baseline %>%
  mutate(
    # corrected brain age prediction
    corrected_pred =  (.pred - abcd_bias_intercept_baseline) / abcd_bias_slope_baseline
  ) %>%
  # corrected corrected brain age gap
  mutate(corrected_gap = corrected_pred - truth)

#Follow-up
brain_age_corrected_df_followup <- brain_age_df_followup %>%
  mutate(
    # corrected brain age prediction
    corrected_pred =  (.pred - bias_intercept) / bias_slope
  ) %>%
  # corrected corrected brain age gap
  mutate(corrected_gap = corrected_pred - truth)


#mine
brain_age_corrected_df_baseline %>%
  metrics(truth = truth, estimate = .pred)

brain_age_corrected_df_baseline %>%
  metrics(truth = truth, estimate = corrected_pred)


brain_age_corrected_df_followup %>%
  metrics(truth = truth, estimate = corrected_pred)


save(brain_age_df_baseline, file="ABCDBaselineBrainAge.Rda")
save(brain_age_corrected_df_baseline, file="ABCDBaselineBrainAgeCorrected.Rda")

save(brain_age_df_followup, file="ABCDFollowUpBrainAge.Rda")
save(brain_age_corrected_df_followup, file="ABCDFollowUpBrainAgeCorrected.Rda")

```

