---
title: "DataSetup"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

packages <-  c("tidyverse",
               "reshape2",
               "nlme", "lme4",
               "data.table", "psych",
               "parallel","lubridate",
               "ggpubr", "broom", 
               "apaTables", "MetBrewer")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)
```


Load Structural Data
```{r}
#Load list of included subjects
struc_include<-rio::import("/Volumes/devbrainlab/ABCD_Data/ABCD4pt0/abcd_imgincl01.txt") %>%
  filter(!collection_title=="collection_title") %>% 
  select(1:12) %>% 
  mutate(interview_age = as.numeric(interview_age),
        imgincl_t1w_include = as.numeric(imgincl_t1w_include),
        imgincl_t2w_include = as.numeric(imgincl_t2w_include)) %>% 
  filter(imgincl_t1w_include == 1)

#Load structural data
#Filter for volume & area measurements
smri_1 <- rio::import("/Volumes/devbrainlab/ABCD_Data/ABCD4pt0/abcd_smrip10201.txt") %>%
  filter(!collection_title=="collection_title") %>% 
  filter(src_subject_id%in%struc_include$src_subject_id) %>% 
  select(matches("vol|area"))
  
#T1 intensity, might not need
smri_2 <- rio::import("/Volumes/devbrainlab/ABCD_Data/ABCD4pt0/abcd_smrip20201.txt") %>%
  filter(!collection_title=="collection_title") %>% 
  filter(src_subject_id%in%struc_include$src_subject_id)

#Rename data to fit naming conventions
#????

```

Load Other Data
```{r}
#Puberty
youth_pds <- rio::import("/Volumes/devbrainlab/ABCD_Data/ABCD4pt0/abcd_ypdms01.txt") %>%
  filter(!collection_title=="collection_title")

youth_pub_sum <- rio::import("/Volumes/devbrainlab/ABCD_Data/ABCD4pt0/abcd_ssphy01.txt") %>%
  filter(!collection_title=="collection_title")

parent_pds <- rio::import("/Volumes/devbrainlab/ABCD_Data/ABCD4pt0/abcd_ppdms01.txt") %>%
  filter(!collection_title=="collection_title")

parent_pub_sum <- rio::import("/Volumes/devbrainlab/ABCD_Data/ABCD4pt0/abcd_ssphp01.txt") %>%
  filter(!collection_title=="collection_title")
  
saliva <- rio::import("/Volumes/devbrainlab/ABCD_Data/ABCD4pt0/abcd_hsss01.txt") %>%
  filter(!collection_title=="collection_title")
  
#Cognition
cognition <- rio::import("/Volumes/devbrainlab/ABCD_Data/ABCD4pt0/abcd_tbss01.txt") %>%
  filter(!collection_title=="collection_title") %>% 
  select(subjectkey, src_subject_id, interview_age, sex, eventname, nihtbx_fluidcomp_fc, nihtbx_cryst_fc, nihtbx_totalcomp_fc)

#Height/weight metrics
physical <- rio::import("/Volumes/devbrainlab/ABCD_Data/ABCD4pt0/abcd_ant01.txt") %>%
  filter(!collection_title=="collection_title")  %>% 
  select(subjectkey, src_subject_id, interview_age, sex, eventname, anthroheightcalc, anthroweightcalc)

#Sexual attraction and behavior
gish <- rio::import("/Volumes/devbrainlab/ABCD_Data/ABCD4pt0/abcd_gish2y01.txt") %>%
  filter(!collection_title=="collection_title") 

#Grade level, parent report
grade <- rio::import("/Volumes/devbrainlab/ABCD_Data/ABCD4pt0/abcd_gish2y01.txt") %>%
  filter(!collection_title=="collection_title") %>% 
  select(subjectkey, src_subject_id, interview_date, interview_age, sex, eventname, demo_ed_v2)
```

Template for renaming sMRI variables
```{r, eval=F}
renamed_smri <- smri_1 %>% 
  rename(new_name = old_name)

FS_InterCranial_Vol = 	smri_vol_scs_intracranialv #technically inter vs intra
FS_BrainSeg_Vol
FS_BrainSeg_Vol_No_Vent
FS_BrainSeg_Vol_No_Vent_Surf
FS_LCort_GM_Vol
FS_RCort_GM_Vol
FS_TotCort_GM_Vol
FS_SubCort_GM_Vol
FS_Total_GM_Vol
FS_SupraTentorial_Vol
FS_SupraTentorial_Vol_No_Vent
FS_SupraTentorial_No_Vent_Voxel_Count
FS_Mask_Vol
FS_BrainSegVol_eTIV_Ratio
FS_MaskVol_eTIV_Ratio
FS_L_LatVent_Vol = smri_vol_scs_ltventriclelh
FS_L_InfLatVent_Vol = smri_vol_scs_inflatventlh
FS_L_Cerebellum_WM_Vol = smri_vol_scs_crbwmatterlh
FS_L_Cerebellum_Cort_Vol = smri_vol_scs_crbcortexlh
FS_L_ThalamusProper_Vol = smri_vol_scs_tplh
FS_L_Caudate_Vol = smri_vol_scs_caudatelh
FS_L_Putamen_Vol = 	smri_vol_scs_putamenlh
FS_L_Pallidum_Vol = 	smri_vol_scs_pallidumlh
FS_3rdVent_Vol = 	smri_vol_scs_3rdventricle
FS_4thVent_Vol = smri_vol_scs_4thventricle
FS_BrainStem_Vol = smri_vol_scs_bstem
FS_L_Hippo_Vol = smri_vol_scs_hpuslh
FS_L_Amygdala_Vol = 	smri_vol_scs_amygdalalh
FS_CSF_Vol = 	smri_vol_scs_csf
FS_L_AccumbensArea_Vol = 	smri_vol_scs_aal
FS_L_VentDC_Vol = smri_vol_scs_vedclh
FS_L_Vessel_Vol
FS_L_ChoroidPlexus_Vol
FS_R_LatVent_Vol = 	smri_vol_scs_ltventriclerh
FS_R_InfLatVent_Vol = smri_vol_scs_inflatventrh
FS_R_Cerebellum_WM_Vol = smri_vol_scs_crbwmatterrh
# no cerebellum cort vol?
FS_R_ThalamusProper_Vol = smri_vol_scs_tprh
FS_R_Caudate_Vol = smri_vol_scs_caudaterh
FS_R_Putamen_Vol = 	smri_vol_scs_putamenrh
FS_R_Pallidum_Vol = smri_vol_scs_pallidumrh
FS_R_Hippo_Vol = 	smri_vol_scs_hpusrh
FS_R_Amygdala_Vol = smri_vol_scs_amygdalarh
FS_R_AccumbensArea_Vol = 	smri_vol_scs_aar
FS_R_VentDC_Vol = smri_vol_scs_vedcrh
FS_R_Vessel_Vol
FS_R_ChoroidPlexus_Vol
FS_OpticChiasm_Vol
FS_CC_Posterior_Vol = smri_vol_scs_ccps
FS_CC_MidPosterior_Vol = smri_vol_scs_ccmidps
FS_CC_Central_Vol = smri_vol_scs_ccct
FS_CC_MidAnterior_Vol = smri_vol_scs_ccmidat
FS_CC_Anterior_Vol = smri_vol_scs_ccat
FS_L_Bankssts_Area = 	smri_area_cdk_banksstslh
FS_L_Caudalanteriorcingulate_Area = smri_area_cdk_cdacatelh
FS_L_Caudalmiddlefrontal_Area = smri_area_cdk_cdmdfrlh
FS_L_Cuneus_Area = 	smri_area_cdk_cuneuslh
FS_L_Entorhinal_Area = smri_area_cdk_ehinallh
FS_L_Fusiform_Area = smri_area_cdk_fusiformlh
FS_L_Inferiorparietal_Area = smri_area_cdk_ifpllh
FS_L_Inferiortemporal_Area = smri_area_cdk_iftmlh
FS_L_Isthmuscingulate_Area = smri_area_cdk_ihcatelh
FS_L_Lateraloccipital_Area = smri_area_cdk_locclh
FS_L_Lateralorbitofrontal_Area = smri_area_cdk_lobfrlh
FS_L_Lingual_Area = smri_area_cdk_linguallh
FS_L_Medialorbitofrontal_Area = smri_area_cdk_mobfrlh
FS_L_Middletemporal_Area = smri_area_cdk_mdtmlh
FS_L_Parahippocampal_Area = smri_area_cdk_parahpallh
FS_L_Paracentral_Area = smri_area_cdk_paracnlh
FS_L_Parsopercularis_Area = smri_area_cdk_parsopclh
FS_L_Parsorbitalis_Area = smri_area_cdk_parsobislh
FS_L_Parstriangularis_Area = smri_area_cdk_parstgrislh
FS_L_Pericalcarine_Area = smri_area_cdk_pericclh
FS_L_Postcentral_Area = smri_area_cdk_postcnlh
FS_L_Posteriorcingulate_Area = smri_area_cdk_ptcatelh
FS_L_Precentral_Area = smri_area_cdk_precnlh
FS_L_Precuneus_Area = smri_area_cdk_pclh
FS_L_Rostralanteriorcingulate_Area = smri_area_cdk_rracatelh
FS_L_Rostralmiddlefrontal_Area = smri_area_cdk_rrmdfrlh
FS_L_Superiorfrontal_Area = smri_area_cdk_sufrlh
FS_L_Superiorparietal_Area = smri_area_cdk_supllh
FS_L_Superiortemporal_Area = smri_area_cdk_sutmlh
FS_L_Supramarginal_Area = smri_area_cdk_smlh
FS_L_Frontalpole_Area = smri_area_cdk_frpolelh
FS_L_Temporalpole_Area = smri_area_cdk_tmpolelh
FS_L_Transversetemporal_Area = smri_area_cdk_trvtmlh
FS_L_Insula_Area = smri_area_cdk_insulalh
FS_R_Bankssts_Area
FS_R_Caudalanteriorcingulate_Area
FS_R_Caudalmiddlefrontal_Area
FS_R_Cuneus_Area
FS_R_Entorhinal_Area
FS_R_Fusiform_Area
FS_R_Inferiorparietal_Area
FS_R_Inferiortemporal_Area
FS_R_Isthmuscingulate_Area
FS_R_Lateraloccipital_Area
FS_R_Lateralorbitofrontal_Area
FS_R_Lingual_Area
FS_R_Medialorbitofrontal_Area
FS_R_Middletemporal_Area
FS_R_Parahippocampal_Area
FS_R_Paracentral_Area
FS_R_Parsopercularis_Area
FS_R_Parsorbitalis_Area
FS_R_Parstriangularis_Area
FS_R_Pericalcarine_Area
FS_R_Postcentral_Area
FS_R_Posteriorcingulate_Area
FS_R_Precentral_Area
FS_R_Precuneus_Area
FS_R_Rostralanteriorcingulate_Area
FS_R_Rostralmiddlefrontal_Area
FS_R_Superiorfrontal_Area
FS_R_Superiorparietal_Area
FS_R_Superiortemporal_Area
FS_R_Supramarginal_Area
FS_R_Frontalpole_Area
FS_R_Temporalpole_Area
FS_R_Transversetemporal_Area
FS_R_Insula_Area
FS_L_Bankssts_GrayVol
FS_L_Caudalanteriorcingulate_GrayVol
FS_L_Caudalmiddlefrontal_GrayVol
FS_L_Cuneus_GrayVol
FS_L_Entorhinal_GrayVol
FS_L_Fusiform_GrayVol
FS_L_Inferiorparietal_GrayVol
FS_L_Inferiortemporal_GrayVol
FS_L_Isthmuscingulate_GrayVol
FS_L_Lateraloccipital_GrayVol
FS_L_Lateralorbitofrontal_GrayVol
FS_L_Lingual_GrayVol
FS_L_Medialorbitofrontal_GrayVol
FS_L_Middletemporal_GrayVol
FS_L_Parahippocampal_GrayVol
FS_L_Paracentral_GrayVol
FS_L_Parsopercularis_GrayVol
FS_L_Parsorbitalis_GrayVol
FS_L_Parstriangularis_GrayVol
FS_L_Pericalcarine_GrayVol
FS_L_Postcentral_GrayVol
FS_L_Posteriorcingulate_GrayVol
FS_L_Precentral_GrayVol
FS_L_Precuneus_GrayVol
FS_L_Rostralanteriorcingulate_GrayVol
FS_L_Rostralmiddlefrontal_GrayVol
FS_L_Superiorfrontal_GrayVol
FS_L_Superiorparietal_GrayVol
FS_L_Superiortemporal_GrayVol
FS_L_Supramarginal_GrayVol
FS_L_Frontalpole_GrayVol
FS_L_Temporalpole_GrayVol
FS_L_Transversetemporal_GrayVol
FS_L_Insula_GrayVol
FS_R_Bankssts_GrayVol
FS_R_Caudalanteriorcingulate_GrayVol
FS_R_Caudalmiddlefrontal_GrayVol
FS_R_Cuneus_GrayVol
FS_R_Entorhinal_GrayVol
FS_R_Fusiform_GrayVol
FS_R_Inferiorparietal_GrayVol
FS_R_Inferiortemporal_GrayVol
FS_R_Isthmuscingulate_GrayVol
FS_R_Lateraloccipital_GrayVol
FS_R_Lateralorbitofrontal_GrayVol
FS_R_Lingual_GrayVol
FS_R_Medialorbitofrontal_GrayVol
FS_R_Middletemporal_GrayVol
FS_R_Parahippocampal_GrayVol
FS_R_Paracentral_GrayVol
FS_R_Parsopercularis_GrayVol
FS_R_Parsorbitalis_GrayVol
FS_R_Parstriangularis_GrayVol
FS_R_Pericalcarine_GrayVol
FS_R_Postcentral_GrayVol
FS_R_Posteriorcingulate_GrayVol
FS_R_Precentral_GrayVol
FS_R_Precuneus_GrayVol
FS_R_Rostralanteriorcingulate_GrayVol
FS_R_Rostralmiddlefrontal_GrayVol
FS_R_Superiorfrontal_GrayVol
FS_R_Superiorparietal_GrayVol
FS_R_Superiortemporal_GrayVol
FS_R_Supramarginal_GrayVol
FS_R_Frontalpole_GrayVol
FS_R_Temporalpole_GrayVol
FS_R_Transversetemporal_GrayVol
FS_R_Insula_GrayVol


```

